/**
 *
 * @copyright &copy; 2010 - 2016, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. All rights reserved.
 *
 * BSD 3-Clause License
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 * 1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 * 2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 * 3.  Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * We kindly request you to use one or more of the following phrases to refer to foxBMS in your hardware, software, documentation or advertising materials:
 *
 * &Prime;This product uses parts of foxBMS&reg;&Prime;
 *
 * &Prime;This product includes parts of foxBMS&reg;&Prime;
 *
 * &Prime;This product is derived from foxBMS&reg;&Prime;
 *
 */

/**
 * @file    version.c
 * @author  foxBMS Team
 * @date    21.09.2015 (date of creation)
 * @ingroup GENERAL
 * @prefix  VER
 *
 * @brief Functions for setting a version number
 *
 */


#include  "version.h"

#define STR(TESTMACRO) #TESTMACRO            /* Results in "RT_EMBEDDED" */
#define XSTR(TESTMACRO) STR(TESTMACRO)         /* Results in "cool" */



/*************************  S E C T I O N     FLASH_HEADER  *****************************/


const VER_ValidStruct_s __attribute__((section (".FLASH_HEADERSection"))) ver_sw_validation =
{
    /* not used (Application-Validation marker) */
    0x11223344,// 0xFFFFFFFFFFFFFFFF,                                                        /*1*/
    /* not used (Application-Invalidation marker) */
    0x0000000000000000,                                                        /*2*/
    /* 32 bit checksum for validating the Application SW (this macro is generated by post build tool)*/
    0,                                                    /*3*/
    0, /*dummy*/
    /* Application SW Version, string of max 7 characters + '\0' */
    VER_SW_VERSION,                                                            /*4*/
    /* Project , string of max 7 characters + '\0' */
    VER_PROJECT,                                                            /*5*/
    0,
    0,0,0, /*dummy_u8_1..3*/
    0, /*dummy*/                                                            /*6*/
    0, /*dummy*/
    11,  /*nr of sections*/                                                    /*7*/
    /* the start address of Application SW */
    (uint32_t)(0),        // (uint32_t)(_START),/*0xA0000000 -> 0x80000000,*/
    ((uint32_t)(0)),                                    /*8*/
    /* the start and end address of interrupt table */
    (uint32_t)0,
    (uint32_t)0,
    /* the start and end address of trap table */
    (uint32_t)(0 ),
    (uint32_t)(0 ),                                                /*10*/
    /* the start and end address of Flashheader */
    (uint32_t)(0 ),
    (uint32_t)(0 ),                                    /*11*/
    /* the start and end address of text-section */
    (uint32_t)(0 ),
    (uint32_t)(0),                                            /*12*/
    /* the start and end address of pcptext-section */
    (uint32_t)(0 ),
    (uint32_t)(0 ),                                            /*13*/
    /* the start and end address of rodata-section */
    (uint32_t)(0 ),
    (uint32_t)(0 ),                                            /*14*/
    /* the start and end address of library text-section */
    (uint32_t)(0 ),
    (uint32_t)(0 ),                                                    /*15*/
    /* the start and end address of pcpdata- and data-section in Flash */
    (uint32_t)(0 ),
    (uint32_t)(0 ),                                            /*16*/

    /* the start and end address of data logging in external NVRAM */
    (uint32_t)(0 ),
    (uint32_t)(0 ),                                            /*17*/

    /* the start and end address of diagnosis memory in external NVRAM */
    (uint32_t)(0 ),
    (uint32_t)(0 ),                                            /*18*/

    /* the total used RAM and Flash size*/
    (uint32_t)(0 ),
    (uint32_t)(0),                                                          /*19*/

    /*dummy_11a, dummy_11b:*/
    0,0,                                                                        /*20*/

    /*12 Byte date format "Mmm dd yyyy"*/
    __DATE__,                                                                    /*21,5*/
    /* 9 Byte time format �hh:mm:ss�, reserved format 12 Byte*/
    __TIME__,                                                                    /*23*/

};

const uint8_t  mytest = 0x12;

/**************************** END OF SECTION FLASH_HEADER *******************************/








